epoch: 500
batch_size: 64
dim: 32
latent_len: 256
g_lr: 0.0025
d_lr: 0.001
soft_label: True
beta: 0.5
lrsh: True
d_acc_thres: 0.8
output_dir: outputs
shape_dir: outputs/shapes
out_model_dir: outputs/models
out_d_loss_dir: outputs/d_loss
out_g_loss_dir: outputs/g_loss
out_d_fake_loss_dir: outputs/d_fake_loss
out_d_real_loss_dir: outputs/d_real_loss
out_d_acc_dir: outputs/d_acc
out_d_fake_acc_dir: outputs/d_fake_acc
out_d_real_acc_dir: outputs/d_real_acc